# Generated by Django 4.1.3 on 2022-12-11 01:02

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nin", models.BigIntegerField(unique=True)),
                ("surname", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=100)),
                ("tel", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sex", models.IntegerField(choices=[(1, "Male"), (2, "Female")])),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=200)),
                (
                    "certificate_of_origin",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="certificates_of_origin",
                    ),
                ),
                (
                    "signature",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="signatures",
                    ),
                ),
                ("secondary_school", models.CharField(max_length=250)),
                ("graduation_year", models.IntegerField()),
                ("current_institution", models.CharField(max_length=100)),
                ("year_of_admission", models.IntegerField()),
                (
                    "id_card",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="id_cards",
                    ),
                ),
                ("course_of_study", models.CharField(max_length=100)),
                ("present_level", models.IntegerField()),
                ("gpa", models.FloatField()),
                (
                    "transcript",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="transcripts",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mother_tel", models.BigIntegerField(blank=True, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("father_tel", models.BigIntegerField(blank=True, null=True)),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "guardian_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("guardian_tel", models.BigIntegerField(blank=True, null=True)),
                (
                    "attestation_letter",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, None],
                        upload_to="attestation_letters",
                    ),
                ),
                ("attestation", models.BooleanField(default=False)),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_lga",
                        to="base.lga",
                    ),
                ),
                (
                    "lga_of_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lga_of_origin",
                        to="base.lga",
                    ),
                ),
            ],
            options={
                "ordering": ["surname"],
            },
        ),
    ]
