# Generated by Django 4.1.3 on 2022-12-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="attestation",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="attestation_letter",
        ),
    ]
