# Generated by Django 4.1.3 on 2022-12-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nin", models.IntegerField(unique=True)),
                ("surname", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=100)),
                ("tel", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sex", models.IntegerField(choices=[(1, "Male"), (2, "Female")])),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=200)),
                ("certificate_of_origin", models.ImageField(upload_to="")),
                ("signature", models.ImageField(upload_to="")),
                ("secondary_school", models.CharField(max_length=250)),
                ("graduation_year", models.DateField()),
                ("current_institution", models.CharField(max_length=100)),
                ("year_of_admission", models.DateField()),
                ("id_card", models.ImageField(upload_to="")),
                ("course_of_study", models.CharField(max_length=100)),
                ("present_level", models.IntegerField()),
                ("gpa", models.FloatField()),
                ("transcript", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mother_tel", models.IntegerField(blank=True, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("father_tel", models.IntegerField(blank=True, null=True)),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "guardian_occupation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("guardian_tel", models.IntegerField(blank=True, null=True)),
                ("attestation_letter", models.ImageField(upload_to="")),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.lga"
                    ),
                ),
            ],
            options={
                "ordering": ["surname"],
            },
        ),
        migrations.DeleteModel(
            name="Profie",
        ),
    ]
