# Generated by Django 4.1.3 on 2022-12-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_profile_delete_profie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lga",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="profile",
            name="lga_of_origin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lga_of_origin",
                to="base.lga",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="lga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_lga",
                to="base.lga",
            ),
        ),
    ]
