# Generated by Django 4.1.3 on 2022-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_profile_attestation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attestation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="attestation_letter",
            field=models.ImageField(
                default="adam.jpg", upload_to="", verbose_name="attestation_letters"
            ),
            preserve_default=False,
        ),
    ]
