# Generated by Django 4.1.3 on 2022-12-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_lga_options_profile_lga_of_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateTimeField(),
        ),
    ]
