# Generated by Django 4.1.3 on 2022-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_profile_graduation_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nin",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tel",
            field=models.BigIntegerField(),
        ),
    ]
