# Generated by Django 4.1.3 on 2022-12-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_profile_nin_alter_profile_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="father_tel",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="guardian_tel",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mother_tel",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
