# Generated by Django 4.1.3 on 2022-12-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_profile_father_tel_alter_profile_guardian_tel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attestation",
            field=models.BooleanField(default=False),
        ),
    ]
