# Generated by Django 4.1.3 on 2022-12-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_profile_attestation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="attestation_letter",
            field=models.ImageField(upload_to="", verbose_name="attestation_letters"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="certificate_of_origin",
            field=models.ImageField(upload_to="certificates_of_origin"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_card",
            field=models.ImageField(upload_to="id_cards"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="signature",
            field=models.ImageField(upload_to="signatures"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="transcript",
            field=models.ImageField(blank=True, null=True, upload_to="transcripts"),
        ),
    ]
